services:
  vscode_web:
    build: 
      args:
        - name=value
      context: .
      dockerfile: ./Dockerfile
      target: unsecure
    container_name: vscode_web
    ports:
      - "3000:3000/tcp"
      - "8080:8080/tcp"
      - "4200:4200/tcp"
    volumes:
      - ./workspace:/home/workspace:cached
    